# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pusblisher',
            new_name='Publisher',
        ),
    ]
